import {defineWorld} from '../shared/world_definition.js';
const emberReachSoundtrackURL = new URL(
  '../../assets/music/ember_reach.mp3',
  import.meta.url,
).href;
import {drawTerrain} from '../shared/terrain_geometry.js';

export const emberReach = defineWorld({
  id: 'ember',
  name: 'Ember Reach',
  description:
    'Low rust-colored foothills, layered volcanic mountains, and glowing crystal fields on a red planet.',
  caption: 'Through the heart of it.',
  music: {
    src: emberReachSoundtrackURL,
    tempo: 104,
    wave: 'triangle',
    melody: [
      69,
      null,
      72,
      76,
      72,
      null,
      69,
      null,
      67,
      null,
      71,
      74,
      71,
      null,
      67,
      null,
      69,
      72,
      76,
      null,
      81,
      76,
      72,
      null,
      67,
      71,
      74,
      null,
      79,
      74,
      71,
      null,
    ],
    bass: [45, 43, 41, 40],
    chords: [
      [57, 60, 64],
      [55, 59, 62],
      [53, 57, 60],
      [52, 56, 59],
    ],
  },
  palette: {
    sky: [0.1, 0.018, 0.036],
    horizon: [0.37, 0.12, 0.085],
    road: [0.095, 0.07, 0.078],
    accent: [1, 0.32, 0.12],
    ground: [0.1, 0.048, 0.045],
  },
  sky: 3,
  ground: true,
  draw(geometryBuilder, sceneFrame) {
    drawTerrain(
      geometryBuilder,
      sceneFrame.distance,
      sceneFrame.centerX,
      sceneFrame.palette,
      false,
      sceneFrame.far,
      sceneFrame.near,
    );
  },
});
