// Convert a selected subset of Kenney's CC0 Space Kit OBJ/MTL files to portable JS.
// Usage: node scripts/ImportKenneySpaceKit.mjs /path/to/unzipped/kenney-space-kit
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { join } from 'node:path';
const root = process.argv[2];
if (!root) throw new Error('Pass the extracted Space Kit directory');
const out = new URL('../examples/src/assets/', import.meta.url);
await mkdir(out, { recursive: true });
const models = {};
for (const name of [
  'satelliteDish',
  'craft_cargoA',
  'rock_crystalsLargeA',
  'rock_largeA',
  'craft_cargoB',
  'craft_speederA',
  'hangar_smallA',
  'machine_generatorLarge',
  'machine_wireless',
  'satelliteDish_detailed',
  'rock_largeB',
  'rock_crystalsLargeB',
]) {
  const colors = {},
    positions = [],
    faces = [];
  let material;
  const mtl = await readFile(join(root, 'Models/OBJ format', `${name}.mtl`), 'utf8');
  for (const line of mtl.split(/\r?\n/)) {
    const [key, ...values] = line.trim().split(/\s+/);
    if (key === 'newmtl') material = values[0];
    if (key === 'Kd') colors[material] = values.map((v) => +Number(v).toFixed(4));
  }
  const obj = await readFile(join(root, 'Models/OBJ format', `${name}.obj`), 'utf8');
  const materials = Object.keys(colors);
  for (const line of obj.split(/\r?\n/)) {
    const [key, ...values] = line.trim().split(/\s+/);
    if (key === 'v') positions.push(values.map((v) => +Number(v).toFixed(5)));
    if (key === 'usemtl') material = values[0];
    if (key === 'f') {
      const indices = values.map((v) => Number(v.split('/')[0]) - 1);
      for (let i = 1; i < indices.length - 1; i++)
        faces.push([indices[0], indices[i], indices[i + 1], materials.indexOf(material)]);
    }
  }
  models[name] = { positions, faces, colors: materials.map((m) => colors[m]) };
  await copyFile(join(root, 'Models/OBJ format', `${name}.obj`), new URL(`${name}.obj`, out));
  await copyFile(join(root, 'Models/OBJ format', `${name}.mtl`), new URL(`${name}.mtl`, out));
  console.log(`${name}: ${faces.length} triangles`);
}
await writeFile(
  new URL('space-kit.js', out),
  `// Kenney Space Kit, CC0. Generated by scripts/ImportKenneySpaceKit.mjs. See THIRD_PARTY.md.\nexport const SPACE_MODELS = ${JSON.stringify(models)};\n`,
);
await copyFile(join(root, 'License.txt'), new URL('KENNEY-LICENSE.txt', out));
